import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "@/styles/page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className={`${inter.className} ${styles.main}`}>{children}</main>
  );
}
