import { Inter } from 'next/font/google'

import styles from '@/styles/page.module.scss'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={`${inter.className} ${styles.main}`}>{children}</main>
      </body>
    </html>
  )
}
