import { ConfigProvider } from 'antd'
import { Inter } from 'next/font/google'

// import '@/styles/globals.scss'
import { themeConfig } from '@/config'
import { AntdProvider } from '@/providers'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Resist To Shitty Environment',
  description: 'Generated by grasswake',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <AntdProvider>
          <ConfigProvider theme={themeConfig}>{children}</ConfigProvider>
        </AntdProvider>
      </body>
    </html>
  )
}
